name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Start Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"Maslinin_Consyzer" /o:"maslinin" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
      - name: Build
        run: dotnet build --configuration Release
      - name: Unit Tests Executing
        run: dotnet test -c "Release" --logger:"txt;LogFileName=consyzer-analyzerengine-report-task.txt" $env:AnalyzerEngineTests
        env:
            AnalyzerEngineTests: Consyzer.AnalyzerEngine.Tests\bin\Release\netcoreapp3.1\Consyzer.AnalyzerEngine.Tests.dll
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            scanMetadataReportFile: Consyzer/TestResults/consyzer-analyzerengine-report-task.txt
      - name: End Analyze
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Publish
        run: dotnet publish
      - name: Upload Artifact - Consyzer Utility
        uses: actions/upload-artifact@v3
        with:
          name: Consyzer
          path: Consyzer\bin\Release
      - name: Upload Artifact - Consyzer.AnalyzerEngine
        uses: actions/upload-artifact@v3
        with:
          name: Consyzer.AnalyzerEngine
          path: Consyzer.AnalyzerEngine\bin\Release\netstandard2.0
